### ISSUE TITLE
Error when running 'brew install dnvm'

### ISSUE THREAD

**Issue by stealthkk** [aspnet/homebrew-dnx#17]
Here is the output:

==> Installing dnvm from aspnet/homebrew-dnx
==> Cloning https://github.com/aspnet/Home.git
Updating /Library/Caches/Homebrew/dnvm--git
==> Checking out branch dev
==> bash -c 'source /usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh; dnvm upgrade'
: command not foundnvm/1.0.0-dev/libexec/dnvm.sh: line 3:
: command not foundnvm/1.0.0-dev/libexec/dnvm.sh: line 18:
'usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh: line 37: syntax error near unexpected token `{
'usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh: line 37: `__dnvm_has() {
bash: dnvm: command not found

**Comment by stealthkk** [comment]
Am I the only one who gets this error?

**Comment by stealthkk** [comment]
I tried untap and tapping it again but it still gives the same error. help!?

**Comment by stealthkk** [comment]
This is still an issue. It would seem it's missing some shell execs.

**Comment by ametzger** [comment]
I had a similar problem after cloning using a git config that converted the line endings from lf to crlf. I set `core.autocrlf` in my git config to false and then ran the brew command again and it worked.

**Comment by stealthkk** [comment]
Well then this author has some things to figure out. I don't see how some git settings should render this project useless on very-close platforms. Please figure out the config for mac and linux.

**Comment by stealthkk** [comment]
Tried your trick and it still does the exact same thing. What is happening here?

**Comment by PureKrome** [comment]
@stealthkk I'm not really able to help .. but .. can you provide some extra info. eg. OS (linux/osx..), etc.. Maybe that might help the repo owners?

**Comment by ametzger** [comment]
Homebrew might be caching the checkout, see if there is something resembling the aspnet/Home repo living in `/Library/Caches`. If you run `git config --list` it should also tell you if autocrlf is set to true, perhaps configured elsewhere.

**Comment by stealthkk** [comment]
Thank you! Deleting /Library/Caches/Homebrew fixed this issue!
