### ISSUE TITLE
Unable to install DNX -> No available formula for dnvm

### ISSUE THREAD

**Issue by PureKrome** [aspnet/homebrew-dnx#18]
Hi,

I'm trying to follow the install instructions for this on `aspnet/home`. There's three steps.

1. `brew tap aspnet/dnx` <- worked.
2. `brew update` <-- took ages .. but it seemed to work.
3. `brew install dnvm` <-- fails

```
 ➜ ~  brew install dnvm
Error: No available formula for dnvm
Searching formulae...
Searching taps...
➜ ~
```

Maybe I didn't do something right??
```
➜  ~  brew tap aspnet/dnx
Warning: Already tapped!
➜  ~
```

Anyone have any suggestions, please?

**Comment by PureKrome** [comment]
Ah - interesting!

With some help from the peeps in JabbR, someone suggested I `untap` then `tap`.

When I did this.. it worked!

So maybe the instructions are the wrong way around? Meaning, when i tapped, that downloaded something. But then the update messed something up.

so maybe it should be ..

1. `brew update`
2. `brew tap aspnet/dnx`
3. `brew install dnvm`

?

**Comment by stealthkk** [comment]
Mine doesn't work either. I always get this output:
==> Installing dnvm from aspnet/homebrew-dnx
==> Cloning https://github.com/aspnet/Home.git
Updating /Library/Caches/Homebrew/dnvm--git
==> Checking out branch dev
==> bash -c 'source /usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh; dnvm upgrade'
: command not foundnvm/1.0.0-dev/libexec/dnvm.sh: line 3:
: command not foundnvm/1.0.0-dev/libexec/dnvm.sh: line 18:
'usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh: line 37: syntax error near unexpected token `{
'usr/local/Cellar/dnvm/1.0.0-dev/libexec/dnvm.sh: line 37: `__dnvm_has() {
bash: dnvm: command not found

**Comment by Jirapong** [comment]
I just put this into blog post - hope this help http://blog.bananacoding.com/blog/first-impressions-of-aspnet-and-visual-studio-code-on-osx

**Comment by postromantic** [comment]
@stealthkk, got exactly the same error. any solutions?

**Comment by Jirapong** [comment]
@stealthkk @postromantic Can you try to 

    rm -rf /Library/Caches/Homebrew

then replace process again?

**Comment by postromantic** [comment]
in my case it was GIT's core.autocrlf setting issue: it must be != true

**Comment by muratg** [comment]
We are not supporting brew based installer anymore. Please follow the instructions [here](http://docs.asp.net/en/latest/getting-started/installing-on-mac.html) to get started on OSX.  Thanks.

**Comment by natemcmaster** [comment]
@muratg should delete this repo altogether then?
