### ISSUE TITLE
Can't tell if aspnet/homebrew-dnx is defunct and/or deprecated

### ISSUE THREAD

**Issue by cmbankester** [aspnet/homebrew-dnx#21]
The current installation instructions for dnvm on OSX (found at https://docs.asp.net/en/latest/getting-started/installing-on-mac.html) recommend installing via the `dnvminstall.sh` script. Since I usually find such installation instructions suspect, I did a cursory search for a Homebrew installation solution for DNVM, and found this repo. It appears, however, that this repo may be defunct or deprecated (the installer for DNVM, for instance, still uses Mono).

Please advise. It would be awesome if DNVM were installable via Homebrew, but if it's not, it seems that this repo should be marked as deprecated.

**Comment by natemcmaster** [comment]
Installing via homebrew is depreciated. cc @muratg we can probably delete this repo now.

FYI DNX is also [being retired](https://github.com/aspnet/dnx#dnx-retired) in favor of https://github.com/dotnet/cli.

**Comment by muratg** [comment]
Yup, we should soon be deleting this repo.  I've updated readme.md for now.

**Comment by cmbankester** [comment]
@natemcmaster @muratg Thanks for the help and the prompt feedback! I'll close this issue out.
