### ISSUE TITLE
this step failed:brew install dnvm

### ISSUE THREAD

**Issue by Genliese** [aspnet/homebrew-dnx#23]
➜  ~ git:(master) ✗ brew install dnvm
Updating Homebrew...
==> Installing dnvm from aspnet/dnx
==> Cloning https://github.com/aspnet/Home.git
Updating /Users/genliese/Library/Caches/Homebrew/dnvm--git
==> Checking out branch dev
Error: No such file or directory - dnvm 

there is no solution to the problem in online. anyone can solve this problem?many thx

**Comment by natemcmaster** [comment]
DNX is deprecated. Use the .NET Core command-line instead: https://docs.microsoft.com/en-us/dotnet/core/tools/
