### ISSUE TITLE
Link to monolite leads to 404

### ISSUE THREAD

**Issue by golergka** [aspnet/homebrew-dnx#9]
The link to monolite in the [kmono.rb](https://github.com/aspnet/homebrew-k/blob/master/kmono.rb#L14) cannot be found on Xamarin server:

```
$ brew install kvm
==> Installing kvm dependency: mono
==> Downloading http://download.mono-project.com/sources/mono/mono-3.8.0.tar.bz2
######################################################################## 100,0%
==> Downloading http://storage.bos.xamarin.com/mono-dist-master/latest/monolite-111-latest.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by muratg** [comment]
We're removing brew support for OSX DNVM installation.  Please see https://github.com/aspnet/homebrew-dnx/issues/20 

cc: @glennc & @anurse .  We'll still need to update the Home repo readme.
